### ISSUE TITLE
09.16 useEffect []에 무슨인자를 줘야 경고메시지 없어짐 && 무한 api 호출 안하는지

### ISSUE THREAD

**Issue by KoGaYoung** [KoGaYoung/movie_review_gy#1]
#09.16 useEffect []에 무슨인자를 줘야 경고메시지 없어짐 + 무한 api 호출 안하는지

![image](https://user-images.githubusercontent.com/36693355/133471582-ad8b23b9-16e6-4a55-aca0-b421ec821c6e.png)

**Comment by KoGaYoung** [comment]
componentDidMount 기능을 사용할 때는 저 warning메시지를 무시해도 됩니다.
// eslint-disable-next-line react-hooks/exhaustive-deps를 deps(두번쨰 인자) 위에 주면 더이상 warning이 발생하지 않습니다.

**Comment by lemphis** [comment]
> componentDidMount 기능을 사용할 때는 저 warning메시지를 무시해도 됩니다.
> // eslint-disable-next-line react-hooks/exhaustive-deps를 deps(두번쨰 인자) 위에 주면 더이상 warning이 발생하지 않습니다.

👍

**Comment by KoGaYoung** [comment]
useEffect (()=> {
    컴디마운트
    return () =>{ 
    컴디 언마운트
    }
    }, []) 

useEffect (()=> {
    컴디업
    }, [etc]) 

useEffect (()=> {
    리랜더링 될때마다 호출
    })
